# Generated by Django 2.0.6 on 2020-11-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarticle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tcategory',
            options={},
        ),
    ]
