# Generated by Django 2.0.6 on 2020-11-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201104_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarticle',
            name='cate_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.TCategory'),
        ),
    ]
