# Generated by Django 2.0.6 on 2020-11-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201104_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarticle',
            name='cate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
