# Generated by Django 2.0.6 on 2020-11-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201104_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarticle',
            name='cate_id',
        ),
        migrations.AddField(
            model_name='tarticle',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.TCategory'),
        ),
    ]
