# Generated by Django 2.0.6 on 2020-11-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201104_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarticle',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
