# Generated by Django 2.0.6 on 2020-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201104_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='salt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
